### ISSUE TITLE
thread 'main' panicked at 'byte index 40 is not a char boundary; it is inside '♫'

### ISSUE THREAD

**Issue by pickfire** [drahnr/cargo-spellcheck#78]
**Describe the bug**

Not handling UTF-8 well

**To Reproduce**
Steps to reproduce the behaviour:

in rust-lang/rust (52d2c7ac948d6abdc18eb9e05a53d03ddcaffd98)

```
> env RUST_BACKTRACE=1 cargo spellcheck
thread 'main' panicked at 'byte index 40 is not a char boundary; it is inside '♫' (bytes 38..41) of `///         println!("♫ Still alive ♫");`', /home/ivan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/str/mod.rs:1920:47
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:490
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::str::slice_error_fail
             at src/libcore/str/mod.rs:0
  14: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::Range<usize>>::index::{{closure}}
  15: cargo_spellcheck::documentation::literalset::LiteralSet::into_chunk
  16: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  17: cargo_spellcheck::documentation::Documentation::extend
  18: cargo_spellcheck::run
  19: cargo_spellcheck::main
  20: std::rt::lang_start::{{closure}}
  21: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  22: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  23: std::panicking::try
             at src/libstd/panicking.rs:274
  24: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  25: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  26: main
  27: __libc_start_main
  28: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Expected behavior**

No can do panic.

**Screenshots**
If applicable, add screenshots or copies of the commandline output to help explain your problem.
Use code blocks

**Pplease complete the following information:**
 - System: [e.g. Fedora, Ubuntu, Win10, MacOS] arch linux
 - Obtained: [i.e. git or cargo] cargo
 - Version: `$(cargo spellcheck --version)` 0.3.0-beta.1

**Additional context**

https://github.com/drahnr/cargo-spellcheck/issues/77

**Comment by drahnr** [comment]
@pickfire tested `v0.3.0-beta.3` on the referenced rust git repo commit checked out, and there are no more panics

**Comment by pickfire** [comment]
Wow, so fast `v0.3.0-beta.3`? I wonder if you could do a `rc` or keep the beta going longer like for a few days or week before release, looks like it's going too fast. Or maybe just checkout a bunch of popular rust git repository and run cargo spellcheck there.

**Comment by drahnr** [comment]
Frankly, not a big fan of beholding fixes for no reason other than "bumping pre release versions too fast". It's a pre-release after all.
I currently don't plan on release candidates

**Comment by pickfire** [comment]
It still breaks.
```
> env RUST_BACKTRACE=1 cargo spellcheck
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-spellcheck-0.3.0-beta.3/src/traverse/iter.rs:36:20
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:490
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1272
  14: cargo_spellcheck::traverse::iter::traverse
  15: cargo_spellcheck::run
  16: cargo_spellcheck::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  20: std::panicking::try
             at src/libstd/panicking.rs:274
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  23: main
  24: __libc_start_main
  25: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by drahnr** [comment]
> It still breaks. Did you pull the submodules as well?

No, you did not state this as part of the reproduction instructions - please check the provided instructions for completeness by executing them from a fresh directory.
